### PR TITLE
App extension compatible

### PR DESCRIPTION
**Pull request by yusefnapora**
This removes the call to [UIApplication sharedApplication] in
WAAppRouteHandler.m, since that method is off-limits to iOS app
extensions.

WAAppRouteHandler's designated initializer has been altered
to accept a rootViewController:(UIViewController *) parameter, which it
uses instead of pulling the rootViewController from the application's
UIWindow.
- [WAAppRouter defaultRouter] has been changed to + [WAAppRouter
  defaultRouterWithRootViewController:(UIViewController)]

With these changes, it is possible to link WAAppRouting into a shared
framework that is linked to both an application and an iOS app
extension.

A downside of passing in the rootViewController is that changes to the 
UIWindow's rootViewController property that are made after initializing 
WAAppRouter won't be picked up.  It might be worth making the 
rootViewController property publicly visible, so that it can be updated if
you change the rootViewController for the window.

### CODE REVIEW

**Comment by yusefnapora** [comment]
I can rebase this branch off of the current master if that would make things easier; you updated to 0.0.2 while I was working on it :)

**Comment by ipodishima** [comment]
Hi @yusefnapora 

Thanks for the PR (already ?!) just released the lib, no ads yet and 50 stars. Not sure where you all guys found me ;)

I can see your issue with watch, did not thought of that.

I'd rather go like AFNetworking (https://github.com/AFNetworking/AFNetworking/issues/2119) with a define. But i'd like your opinion on it.
It just seems heavy to add this parameter for a recovery presentation controller

**Comment by yusefnapora** [comment]
I guess you're giving the people what they want :smile: 

 I agree that it's awkward to have to pass in an extra parameter for this edge case.  I think you're right that a define would be a good way to do it.  And if you are in an app extension, and have the flag set, it's on you to ensure that `presentingViewController` is non-nil.

I'll make a new branch with that, if you like :)

**Comment by ipodishima** [comment]
Yes, would be great!

Thanks

Don't worry about travis commits disappeared, I finally dropped it after having issues with configuration. Will see that later

**Pull request closed without merging**
